spring:
  datasource:
    url: jdbc:postgresql://${DB_USERNAME}:${DB_PASSWORD}@ep-jolly-wildflower-adb7ezzg-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
