spring:
  datasource:
    url: jdbc:postgresql://your-neon-endpoint/your-database-name?sslmode=require
    username: your-username
    password: your-password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
